inherits = "yo"

"ui.background" = { bg = "#020202" }
# "ui.background" = {}
# background = '#020202'

# code
variable = { fg = "s10" }
namespace = { fg = "p10" }
punctuation = { fg = "p9" }
"punctuation.delimiter" = { fg = "p8" }
function = { fg = "s11" }
attribute = { fg = "s10" }
tag = { fg = "keyword" }
label = { fg = "p12" }
constructor = { fg = "p12" }
type = { fg = "s12" }

# cursor/selection
"ui.cursor.primary" = { fg = "p12", bg = "#ff0000" }
"ui.selection.primary" = { bg = "a5" }
"ui.cursorline.primary" = { bg = "a2", underline = { color = "a5", style = "line" }}

# bufferline/statusline
"ui.bufferline" = { fg = "p11", bg = "" }
"ui.bufferline.active" = { fg = "p1", bg = "p11"}
"ui.statusline" = { fg = "p11", bg = "" }
"ui.statusline.inactive" = { fg = "p11", bg = "" }
"ui.statusline.normal" = { fg = "p2", bg = "" }
"ui.statusline.insert" = { fg = "p2", bg = "" }
"ui.statusline.select" = { fg = "p2", bg = "" }
"ui.statusline.separator" = { fg = "p7" }

# diagnostics
"diagnostic.error" = { underline = { color = "error", style = "curl" }}
"diagnostic.warning" = { underline = { color = "warning", style = "curl" }}
"diagnostic.info" = { underline = { color = "info", style = "curl" }}
"diagnostic.hint" = { underline = { color = "hint", style = "curl" }}
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }
"diagnostic.unnecessary" = { modifiers = ["dim"] }

error = { fg = "error" }
warning = { fg = "warning" }
info = { fg = "constant" }
hint = { fg = "hint", modifiers = ["dim"] }

# locals
"local" = { underline = { color = "info", style = "curl" }}

# virtual
"ui.virtual.jump-label" = { fg = "p12", modifiers = [
  "bold",
], underline = {} }
"ui.virtual.inlay-hint" = { fg = "p7", modifiers = ["italic"] }
"ui.virtual.whitespace" = { fg = "p4" }

# line numbers / diff
"ui.linenr" = { fg = "s8" }
"ui.linenr.selected" = { fg = "s12" }
"diff.plus" = { fg = "diff_add" }
"diff.delta" = { fg = "warning" }
"diff.minus" = { fg = "error" }

# https://www.radix-ui.com/colors
[palette]
info = "#7d66d9"     # iris-10

string = "#ffd60a"   # amber-10
constant = "#a8eeff" # sky-10

diff_add = "#33b074" # green-10
hint = "#3b9eff"     # blue-10 

# amber
a1 = "#16120c"
a2 = "#1d180f"
a3 = "#302008"
a4 = "#3f2700"
a5 = "#4d3000"
a6 = "#5c3d05"
a7 = "#714f19"

# slate
s1 = "#111113"
s2 = "#18191b"
s3 = "#212225"
s4 = "#272a2d"
s5 = "#2e3135"
s6 = "#363a3f"
s7 = "#43484e"
s8 = "#5a6169"
s9 = "#696e77"
s10 = "#777b84"
s11 = "#b0b4ba"
s12 = "#edeef0"

