[general]
import = ["~/.config/alacritty/theme.toml"]

[colors.cursor]
cursor = "0xff00ff"
text = "0xeceeed"

[cursor]
thickness = 0.4
style = { shape = "Beam" }
vi_mode_style = "Block"

[font]
size = 14.0

[font.normal]
family = "ZedMono Nerd Font"

[window]
dynamic_padding = true
decorations = "buttonless"
option_as_alt = "Both"
startup_mode = "Maximized"

[keyboard]
bindings = [
  # { key = "Escape", mods = "Control", action = "ToggleViMode" },
  # TODO: didn't do anything when I checked
  # { key = "I", mode = "Vi|~Search", action = "ToggleViMode" },
]
