# theme = "modus_operandi_tinted"
theme = "yo_modified"

# [theme]
# dark = "yo_modified"
# light = "yo_light_modified"

[keys.normal.space.t]
"0" = ":theme github_light"
"6" = ":theme yo_modified"
"7" = ":theme gruvbox_light"
"8" = ":theme yo_light"
"9" = ":theme flatwhite"
# run rust unit tests using %{buffer_name} to construct module path
t = [
  ":sh RUSTFLAGS=-Awarnings cargo test -q -- --nocapture %sh{echo %{buffer_name} | sed -E 's|^src/||; s|/mod\\.rs$||; s|\\.rs$||; s|/|::|g' }",
]

[editor]
bufferline = "always"
scrolloff = 30
line-number = "relative"
default-yank-register = '+'
mouse = false
cursorline = true
color-modes = true
completion-trigger-len = 2
shell = ['fish', '-c']
completion-timeout = 5
# FIXME: ruler is ugly rn - update when ruler looks prettier
# rulers = [80]
text-width = 80
jump-label-alphabet = "tnseriplfuwydhcxoaqz"

[editor.whitespace.render]
space = "all"
newline = "all"

[editor.whitespace.characters]
space = "¬∑"
newline = "‚èé"

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.auto-save]
after-delay.enable = true
after-delay.timeout = 0

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = [
  "mode",
  "spinner",
  "version-control",
  "file-absolute-path",
  "read-only-indicator",
  "file-modification-indicator",
  "diagnostics",
]
# center = [
#   "file-absolute-path"
# ]
right = [
  "workspace-diagnostics",
  "position",
  "file-encoding",
]
mode = { normal = "ü¶ä NOR", insert = "ü™∂ INS", select = "üîç SEL" }

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true
display-progress-messages = true

[keys.normal]
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"
X = "select_line_above"
"," = "repeat_last_motion"
esc = ["collapse_selection", "keep_primary_selection", ":w"]
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection", ":w"]
# Like in principle but buggy with auto format on save...
# o = ["open_below", "normal_mode"]
# O = ["open_above", "normal_mode"]

[keys.insert]
S-tab = "move_parent_node_start"

[keys.select]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"
"," = "repeat_last_motion"
D = ["extend_to_line_bounds", "delete_selection", "normal_mode"]

[keys.normal.space]
# toggle diagnostic levels
# TODO: redo this when https://github.com/helix-editor/helix/pull/12203 lands
d = [":toggle inline-diagnostics.other-lines error warning", ":toggle end-of-line-diagnostics error warning"]
i = ":toggle lsp.display-inlay-hints"
x = [":bc"]
# yazi
e = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
# find and replace using scooter
s = [
    ":write-all",
    ":insert-output scooter --no-stdin >/dev/tty",
    ":redraw",
    ":reload-all"
]
# lazygit
g = [
    ":write-all", 
    ":new", 
    ":insert-output lazygit", 
    ":buffer-close!", 
    ":redraw", 
    ":reload-all"
]
# config
"," = ":config-open"
"C-," = ":config-reload"
# open first diagnostic in bacon-locations
E = ":open %sh{head -n 1 .bacon-locations}"
# daily journal
j = ":open %sh{daily_journal}"

[editor.indent-guides]
render = true
character = '‚îä' # Some characters that work well: "‚ñè", "‚îÜ", "‚îä", "‚∏Ω" 
skip-levels = 1

