[theme]
dark = "rosewood-blue"
light = "gruvbox_light"

[keys.normal.space.t]
"0" = ":theme github_light"
"1" = ":theme wolf-alabaster-light-bg"
"3" = ":theme wolf-alabaster-dark"
"4" = ":theme rosewood-green"
"5" = ":theme rosewood-blue"
"6" = ":theme rosewood"
"7" = ":theme gruvbox_light"
"8" = ":theme yo_light"
"9" = ":theme flatwhite_modified"
# run rust unit tests using %{buffer_name} to construct module path
t = [
  ":sh RUSTFLAGS=-Awarnings cargo test -q -- --nocapture %sh{echo %{buffer_name} | sed -E 's|^src/||; s|/mod\\.rs$||; s|\\.rs$||; s|/|::|g' }",
]

[editor]
bufferline = "always"
scrolloff = 30
line-number = "relative"
default-yank-register = '+'
mouse = false
cursorline = true
color-modes = true
completion-trigger-len = 2
shell = ['fish', '-c']
completion-timeout = 5
# FIXME: ruler is ugly rn - update when ruler looks prettier
# rulers = [80]
text-width = 80
jump-label-alphabet = "tnseriplfuwydhcxoaqz"

[editor.statusline]
left = [
  "mode",
  "spinner",
  "version-control",
  # more centered to have it on left currently
  "file-absolute-path",
  "read-only-indicator",
  "file-modification-indicator",
  "diagnostics",
]
# center = [
#   "file-absolute-path"
# ]
right = [
  "workspace-diagnostics",
  "position",
  "file-encoding",
]
mode = { normal = "ðŸ¦Š NOR", insert = "ðŸª¶ INS", select = "ðŸ” SEL" }

[editor.lsp]
display-progress-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.auto-save]
after-delay.enable = true
after-delay.timeout = 0

[editor.whitespace.render]
space = "all"
newline = "all"
[editor.whitespace.characters]
space = "Â·"
newline = "âŽ"

[editor.indent-guides]
render = true
character = 'â”Š' # Some characters that work well: "â–", "â”†", "â”Š", "â¸½" 
skip-levels = 1

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.word-completion]
trigger-length = 3

[keys.normal]
x = ["extend_to_line_bounds", "select_mode"]
X = ["extend_line_below"]
esc = ["collapse_selection", "keep_primary_selection", ":w"]
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"
"," = "repeat_last_motion"
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection", ":w"]
";" = "flip_selections"
ret = "@gw"

[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode", ":w"]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"
"," = "repeat_last_motion"
D = ["extend_to_line_bounds", "delete_selection", "normal_mode"]
"g" = { "e" = "extend_to_file_end" }
";" = "flip_selections"
ret = "@gw"

[keys.insert]
S-tab = "move_parent_node_start"

[keys.normal.space]
# toggle diagnostic levels
# TODO: redo this when https://github.com/helix-editor/helix/pull/12203 lands
# d = [":toggle inline-diagnostics.other-lines error warning", ":toggle end-of-line-diagnostics error warning"]
i = ":toggle lsp.display-inlay-hints"
x = [":bc"]
# yazi
e = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
# find and replace using scooter
R = [
    ":write-all",
    ":insert-output scooter --no-stdin >/dev/tty",
    ":redraw",
    ":reload-all"
]
# lazygit
g = [
    ":write-all", 
    ":new", 
    ":insert-output lazygit", 
    ":buffer-close!", 
    ":redraw", 
    ":reload-all"
]
# config
# "," = ":config-open"
# "C-," = ":config-reload"
# open first diagnostic in bacon-locations
# E = ":open %sh{head -n 1 .bacon-locations}"
# shows a diagnostic picker that shows errors only
E = "@ D%sev error"
# daily journal
j = ":open %sh{daily_journal}"
# TODO: wanna get smartcat output in a new buffer - I think that would be best
# space = [
#   ":vs",
#   ":n",
# ]

# config
[keys.normal.space.","]
"c" = ":config-open"
"l" = ":open ~/.config/helix/languages.toml"
"r" = ":config-reload"

