theme = "modus_operandi_tinted"

[keys.normal.space.t]
"0" = ":theme github_light"
"1" = ":theme ao"
"2" = ":theme hex_lavender_modified"
"3" = ":theme gruber-darker"
"4" = ":theme rose_pine"
"5" = ":theme yo"
"6" = ":theme ferra"
"7" = ":theme gruvbox_light"
"8" = ":theme modus_operandi_tinted"
"9" = ":theme flatwhite"
# run rust unit tests using %{buffer_name} to construct module path
t = [
  ":sh RUSTFLAGS=-Awarnings cargo test -q -- --nocapture %sh{echo %{buffer_name} | sed -E 's|^src/||; s|/mod\\.rs$||; s|\\.rs$||; s|/|::|g' }",
]

[editor]
bufferline = "never"
scrolloff = 15
line-number = "relative"
default-yank-register = '+'
mouse = false
cursorline = true
color-modes = true
completion-trigger-len = 2
shell = ['fish', '-c']
completion-timeout = 5
# FIXME: ruler is ugly rn - update when ruler looks prettier
# rulers = [80]
text-width = 80
jump-label-alphabet = "tnseriplfuwydhcxoaqz"
# end-of-line-diagnostics = "hint"
end-of-line-diagnostics = "warning"

[editor.whitespace.render]
space = "all"
# newline = "all"

[editor.whitespace.characters]
space = "·"
# newline = "⏎"

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.auto-save]
after-delay.enable = true
after-delay.timeout = 0

[editor.cursor-shape]
insert = "bar"
# insert = "block"
normal = "block"
select = "underline"

[editor.statusline]
left = [
  "mode",
  "spinner",
  "version-control",
  "read-only-indicator",
  "file-modification-indicator",
  "diagnostics"
]
center = [
  "file-absolute-path"
]
right = [
  "workspace-diagnostics",
  "position",
  "file-encoding",
]

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true
display-progress-messages = true

[keys.normal]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"
X = "select_line_above"
esc = ["collapse_selection", "keep_primary_selection"]

[keys.insert]
S-tab = "move_parent_node_start"

[keys.select]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"

# TODO: <space><E> - open diagnostic picker of just errors

[keys.normal.space]
# today's journal
j = [':open %sh{daily_journal}']
i = ":toggle lsp.display-inlay-hints"
x = ":bc"
# yazi
e = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
# lazygit
g = [
    ":write-all", 
    ":new", 
    ":insert-output lazygit", 
    ":buffer-close!", 
    ":redraw", 
    ":reload-all"
]
# FIXME: need to use diff char for this - overlaps with local diagnostic search
# toggle diagnostics
# "d" = [
#     ":toggle-option inline-diagnostics.cursor-line warning hint disable",
#     ":toggle-option inline-diagnostics.other-lines warning hint disable",
# ]

[editor.indent-guides]
render = true
character = '┊' # Some characters that work well: "▏", "┆", "┊", "⸽" 
skip-levels = 1

