# snippets
[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
max_completion_items = 100  # set max completion results len for each group: words, snippets, unicode-input
feature_words = true  # enable completion by word
feature_snippets = true  # enable snippets
snippets_first = false  # completions will return before snippets by default
snippets_inline_by_word_tail = false  # suggest snippets by WORD tail, for example text `xsq|` become `x^2|` when snippet `sq` has body `^2`
feature_unicode_input = false  # enable "unicode input"
feature_paths = false  # enable path completion
feature_citations = false  # enable citation completion (only on `citation` feature enabled)

[language-server.scls.environment]
RUST_LOG = "info,simple-completion-language-server=info"
LOG_FILE = "/tmp/completion.log"

# colors
[language-server.uwu_colors]
command = "uwu_colors"

[language-server.rust-analyzer.config]
cargo = { features = "all", targetDir = true }
check = { command = "clippy" }

# --------------------json--------------------
[language-server.vscode-json-language-server]
config = { "provideFormatter" = true, "json" = { "keepLines" = { "enable" = true } } }

# --------------------rust--------------------
[[language]]
name = "rust"
auto-format = true
language-servers = ["scls", "rust-analyzer", "uwu_colors"]

[language.auto-pairs]
'(' = ")"
'[' = "]"
'{' = "}"
'"' = '"'
'`' = "`"
'<' = ">"
'|' = "|"

# --------------------toml--------------------
[[language]]
name = "toml"
auto-format = true
language-servers = ["tombi", "uwu_colors"]

[[language]]
name = "json"
language-servers = ["scls", "vscode-json-language-server"]

# --------------------markdown--------------------
[[language]]
name = "markdown"
language-servers = ["marksman"]
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"] }
auto-format = true
text-width = 120
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true
soft-wrap.wrap-indicator = ""
