theme = "modus_operandi_tinted"

[editor]
scrolloff = 1
line-number = "relative"
default-yank-register = '+'
mouse = false
cursorline = true
bufferline = "always"
color-modes = true
completion-trigger-len = 2
shell = ['fish', '-c']
completion-timeout = 5
jump-label-alphabet = "tnseriplfuwydhcxoaqz"
end-of-line-diagnostics = "hint"
gutters = ["spacer"]
auto-info = false

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.auto-save]
after-delay.enable = true
after-delay.timeout = 0

[editor.cursor-shape]
insert = "bar"
# insert = "block"
normal = "block"
select = "underline"

[editor.statusline]
mode.normal = ""
mode.insert = ""
mode.select = ""
left = []
right = []

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true
display-progress-messages = true

[keys.normal]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"
X = "select_line_above"
esc = ["collapse_selection", "keep_primary_selection"]

[keys.insert]
S-tab = "move_parent_node_start"

[keys.select]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"

[keys.normal.space]
x = ":bc"

[editor.indent-guides]
render = true
character = '┊' # Some characters that work well: "▏", "┆", "┊", "⸽" 
skip-levels = 1

